### PR TITLE
Create A pull Request To merge With Master Branch

### PR DESCRIPTION
**Pull request by mohamednaser**

### CODE REVIEW

**Review by Forison — COMMENTED** [review]
# Pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi team 👋👋
you have done a good job on this project👋👋. your readme file is fantastic👌
Here are a few changes we have to make to get this project approved. Don't worry you are almost there🙂.
* [ ] navbar
- The navbar has three breakpoints and at each breakpoint, it behaves differently🙂.
> take a look at the TNW logo see how it changes at each breakpoint
> Check the search icon logo it does not look too good now🙂 using(font-awesome won't be a bad idea)
- The fixed nature of the navbar is making it take the space between the navbar and the first section, give an appropriate margin to the main body to get a good spacing🙂 
> I like to give the main body a margin-top of 60px, see if that is applicable in your case.

* [ ] Remove comments from ```stylesheets``` and ```index.html```
### That is it guys you are almost there,😇😇😇
## Kindly, make the changes I have pointed out and submit for review

feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. I would be happy to assist you.🙂

Happy coding

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great Progress :clap: . However, the implementation of the changes are not as the reviewer requested. check below :arrow_down: 

##### Navigation bar REQUIREMENT :red_circle: 

###### Large version

* [ ] It contains main navigation row.
* [ ] It contains sub-navigation row.
* [ ] It contains search icon at the rightmost side of sub-navigation row.

###### Medium version changes

* [ ] TWN logo appears at the leftmost part.

###### Small version changes

* [ ] Navigation and sub-navigation row changes to a hamburger (bars) icon at the rightmost part (next to seach icon).

 ### Please implement the requirements above. When finished, resubmit another code review request :pray:

**Review by uche-inyama — APPROVED** [review]
Hi team! nice job :clap: 

You have implemented the requested changes. 

[**Making your pull request look professional**] 
Moving forward, the title of your pull request should be descriptive, for example: **```A code review request for next-web-clone```**

Go ahead and merge with the master branch.

#### ``` Have a great day``` :slightly_smiling_face:

**Pull request merged**
